### ISSUE TITLE
SplitterComponent doesn't dispose itself properly

### ISSUE THREAD

**Issue by wooferzfg** [ShootMe/LiveSplit.Celeste#2]
This method should remove the event handlers that the component created in the constructor: https://github.com/ShootMe/LiveSplit.Celeste/blob/master/SplitterComponent.cs#L329

As an example, the Video Component does this: https://github.com/LiveSplit/LiveSplit.Video/blob/594114361c5317ac204c32ae947b41c28a4304c2/VideoComponent.cs#L244
You won't need the base.Dispose() though, since you're just implementing IComponent.

I believe that this causes the Celeste Auto Splitter to mess up other Auto Splitters if you don't restart LiveSplit when switching games. With A Hat in Time, it seems to reset the IGT to 0 when finishing a run.

**Comment by ShootMe** [comment]
I've never experienced that, so it seems odd. I went ahead and removed the event handlers there though.
